DROP DATABASE IF EXISTS
employee_db;

CREATE DATABASE employee_db;

USE employee_db;

DROP TABLE IF EXISTS department;

CREATE TABLE department (
id INT NOT NULL PRIMARY KEY,
dep_name VARCHAR(30) NOT NULL,
);

DROP TABLE IF EXISTS role;

CREATE TABLE role (
id INT NOT NULL PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INT NOT NULL
);



